In [2]:
import torch, torchvision

In [3]:
# Import a resnet18 pretrained model
model = torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to C:\Users\Ahmed/.cache\torch\checkpoints\resnet18-5c106cde.pth
100.0%


In [88]:
# Define the data (1 image with 3 color channels that is 64x64) and the labels
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [89]:
# Predictions from the model over the data.
prediction = model(data)
# Loss as a sum of difference betwee the actual and the expected.
loss = (prediction - labels).sum()
# Backprop on the parameters of the model (Stored in each parameters .grad)
loss.backward()
loss

tensor(-4.0184e+11, grad_fn=<SumBackward0>)

In [90]:
for i in model.parameters():
    print(i.grad)


tensor([[[[-2.3233e+03,  1.3115e+04,  7.8262e+03,  ...,  1.0026e+04,
            2.8597e+02,  1.4031e+04],
          [ 1.4644e+04, -1.4776e+04,  1.0558e+04,  ..., -1.1603e+03,
           -1.0923e+04, -5.5132e+02],
          [ 3.0296e+03, -8.2702e+02, -7.3446e+03,  ...,  6.1311e+03,
            2.7696e+03,  3.1087e+03],
          ...,
          [-3.0992e+03,  4.8669e+03, -9.3306e+03,  ...,  2.1655e+03,
           -2.3353e+03,  3.3416e+03],
          [ 6.9126e+02, -1.0512e+03, -1.8114e+03,  ...,  3.2187e+02,
           -1.1424e+04, -1.0737e+04],
          [ 3.5188e+02, -2.8334e+03,  1.4621e+04,  ..., -5.9873e+03,
            1.5759e+02, -4.0639e+03]],

         [[ 1.5621e+03,  6.5146e+02,  2.5776e+01,  ...,  7.4734e+03,
           -1.6014e+04,  4.8010e+02],
          [ 6.7700e+03, -2.0657e+03, -2.8904e+03,  ..., -3.4315e+03,
            5.7609e+03,  5.4726e+03],
          [-3.0111e+03,  9.8316e+03,  2.5236e+03,  ...,  1.0642e+04,
           -4.4351e+03,  3.9432e+03],
          ...,
     

In [93]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)
optim.step()

In [98]:
# Differentiation in Autograd

# Assume a, b are parameters in a NN
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

# Assume Q is the error at the end of a NN
Q = 3*a**3 - b**2

In [99]:
external_grad = torch.tensor([1., 1.])
Q.backward(external_grad)

In [103]:
print(a.grad == 9*a**2)
print(b.grad == -2*b)

tensor([True, True])
tensor([True, True])
