In [2]:
import torch
import numpy as np

In [5]:
# Create a tensor from an n-dimensional array.
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [9]:
# Create a tensor from an np-array
np_array   = np.array(data)
x_np_array = torch.from_numpy(np_array)
x_np_array

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [15]:
# Create a tensor from another tensor (Retains the shpae and datatype of the input tensor)
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"rand tensor: \n {x_rand} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

rand tensor: 
 tensor([[0.2411, 0.0495],
        [0.5761, 0.8408]]) 



In [20]:
# You can create tensors using a shape defining tuple with the dimensions.
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor= torch.zeros(shape)
print(f"rand tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Ones tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.9869, 0.6382, 0.8557],
        [0.5978, 0.9526, 0.5155]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Ones tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [21]:
# Tensor attributes
tensor = torch.rand(3, 4)
print(f"tensor shape: \n {tensor.shape} \n")
print(f"tensor type: \n {tensor.dtype} \n")
print(f"tensor device: \n {tensor.device} \n")

tensor shape: 
 torch.Size([3, 4]) 

tensor type: 
 torch.float32 

tensor device: 
 cpu 



In [24]:
if torch.cuda.is_available():
    print("Available")
    tensor = tesnor.to('cuda')

In [26]:
# Make the column at index 1 element's be all 0
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [32]:
# Concatenate tensors together
t0 = torch.cat([tensor, tensor, tensor], dim=0)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [34]:
# Multiplying tensors
print(f"using .mul =>  {tensor.mul(tensor)} \n")
print(f"using * =>  {tensor * tensor} \n")

using .mul =>  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

using * =>  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [35]:
# Matrix multiplication on tensors.
print(f"using .matmul =>  {tensor.matmul(tensor.T)} \n")
print(f"using @ =>  {tensor @ tensor} \n")

using .matmul =>  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

using @ =>  tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]]) 



In [37]:
# In-place operations (Discouraged for computing derivatives because of the immediate loss of history)
print(tensor, "\n")
tensor.add_(5)
print(tensor, "\n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [40]:
# Bridge to numpy
t = torch.ones(5)
print(t, "\n")

# Refering to the same address.
n = t.numpy()

# in-place changes are applied to both.
t.add_(3)

print(n, "\n")

tensor([1., 1., 1., 1., 1.]) 

[4. 4. 4. 4. 4.] 



In [42]:
# numpy to tensor
n = np.ones(5)
print(n, "\n")

# Refering to the same address.
t = torch.from_numpy(n)

# in-place changes are applied to both.
np.add(n, 1, out=n)

print(t, "\n")

[1. 1. 1. 1. 1.] 

tensor([2., 2., 2., 2., 2.], dtype=torch.float64) 

